{$ifdef ver100}
{$define fcDelphi3Up}
{$define fcDelphi3}
{$define fcDelphi3Only}
{$endif}

{$ifdef ver110}
{$define fcDelphi3Up}
{$define fcDelphi3}
{$ObjExportAll On}
{$endif}

{$ifdef ver120}
{$define fcDelphi3Up}
{$define fcDelphi4Up}
{$endif}

{$IFDEF VER125}
{$define fcDelphi3Up}
{$define fcDelphi4Up}
{$ObjExportAll On}
{$ENDIF}

{$ifdef ver130}
{$define fcDelphi3Up}
{$define fcDelphi4Up}
{$define fcDelphi5Up}
{$define fcDelphi5}
{$endif}

{$IFDEF VER140}
{$define fcDelphi3Up}
{$define fcDelphi4Up}
{$define fcDelphi5Up}
{$define fcDelphi6Up}
{$define fcDelphi6}
{$ENDIF}

